# Generated by Django 4.2.1 on 2023-05-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("paddleApp", "0001_initial"),
  ]

  operations = [
    migrations.AddField(
      model_name="ocr_record",
      name="after_txt",
      field=models.TextField(null=True, verbose_name="检测之后的敏感词汇"),
    ),
  ]
